/**
 * Coloring-book style thumbnail URLs using OpenMoji black-outline SVGs.
 * These are free, open-source (CC BY-SA 4.0) black-outline illustrations —
 * exactly the kind of clean line art suitable for children to color.
 * URL format: https://openmoji.org/data/black/svg/{CODEPOINT}.svg
 */

const OM = (code: string) => `https://openmoji.org/data/black/svg/${code}.svg`;

export const PHOTO_MAP: Record<string, string> = {

  // ══════════════════ ANIMALS (main library, no prefix) ══════════════════
  'lion':         OM('1F981'),
  'elephant':     OM('1F418'),
  'tiger':        OM('1F42F'),
  'giraffe':      OM('1F992'),
  'zebra':        OM('1F993'),
  'bear':         OM('1F43B'),
  'wolf':         OM('1F43A'),
  'fox':          OM('1F98A'),
  'rabbit':       OM('1F430'),
  'cat':          OM('1F431'),
  'dog':          OM('1F436'),
  'horse':        OM('1F434'),
  'cow':          OM('1F42E'),
  'sheep':        OM('1F411'),
  'pig':          OM('1F437'),
  'chicken':      OM('1F414'),
  'duck':         OM('1F986'),
  'parrot':       OM('1F99C'),
  'eagle':        OM('1F985'),
  'owl':          OM('1F989'),
  'penguin':      OM('1F427'),
  'flamingo':     OM('1F9A9'),
  'peacock':      OM('1F99A'),
  'swan':         OM('1F9A2'),
  'hummingbird':  OM('1F426'),
  'crocodile':    OM('1F40A'),
  'alligator':    OM('1F40A'),
  'snake':        OM('1F40D'),
  'lizard':       OM('1F98E'),
  'chameleon':    OM('1F98E'),
  'gecko':        OM('1F98E'),
  'tortoise':     OM('1F422'),
  'turtle':       OM('1F422'),
  'frog':         OM('1F438'),
  'fish':         OM('1F41F'),
  'shark':        OM('1F988'),
  'whale':        OM('1F40B'),
  'dolphin':      OM('1F42C'),
  'octopus':      OM('1F419'),
  'jellyfish':    OM('1F9DF'), // use ghost outline as fallback for jellyfish
  'crab':         OM('1F980'),
  'lobster':      OM('1F99E'),
  'starfish':     OM('2B50'),
  'butterfly':    OM('1F98B'),
  'bee':          OM('1F41D'),
  'ladybug':      OM('1F41E'),
  'dragonfly':    OM('1F98B'),
  'ant':          OM('1F41C'),
  'snail':        OM('1F40C'),
  'spider':       OM('1F577'),
  'scorpion':     OM('1F982'),
  'hamster':      OM('1F439'),
  'squirrel':     OM('1F43F'),
  'raccoon':      OM('1F99D'),
  'hedgehog':     OM('1F994'),
  'bat':          OM('1F987'),
  'deer':         OM('1F98C'),
  'monkey':       OM('1F412'),
  'gorilla':      OM('1F98D'),
  'cheetah':      OM('1F406'),
  'leopard':      OM('1F406'),
  'hippo':        OM('1F99B'),
  'rhino':        OM('1F98F'),
  'camel':        OM('1F42A'),
  'kangaroo':     OM('1F998'),
  'koala':        OM('1F428'),
  'panda':        OM('1F43C'),
  'polar-bear':   OM('1F43B'),
  'seal':         OM('1F9AD'),
  'walrus':       OM('1F9AD'),

  // ══════════════════ ANIMALS (animal- prefix from extra library) ══════════════
  'animal-lion':         OM('1F981'),
  'animal-elephant':     OM('1F418'),
  'animal-tiger':        OM('1F42F'),
  'animal-giraffe':      OM('1F992'),
  'animal-zebra':        OM('1F993'),
  'animal-bear':         OM('1F43B'),
  'animal-wolf':         OM('1F43A'),
  'animal-fox':          OM('1F98A'),
  'animal-rabbit':       OM('1F430'),
  'animal-cat':          OM('1F431'),
  'animal-dog':          OM('1F436'),
  'animal-horse':        OM('1F434'),
  'animal-cow':          OM('1F42E'),
  'animal-sheep':        OM('1F411'),
  'animal-pig':          OM('1F437'),
  'animal-chicken':      OM('1F414'),
  'animal-duck':         OM('1F986'),
  'animal-parrot':       OM('1F99C'),
  'animal-eagle':        OM('1F985'),
  'animal-owl':          OM('1F989'),
  'animal-penguin':      OM('1F427'),
  'animal-flamingo':     OM('1F9A9'),
  'animal-peacock':      OM('1F99A'),
  'animal-swan':         OM('1F9A2'),
  'animal-hummingbird':  OM('1F426'),
  'animal-crocodile':    OM('1F40A'),
  'animal-alligator':    OM('1F40A'),
  'animal-snake':        OM('1F40D'),
  'animal-lizard':       OM('1F98E'),
  'animal-chameleon':    OM('1F98E'),
  'animal-gecko':        OM('1F98E'),
  'animal-tortoise':     OM('1F422'),
  'animal-turtle':       OM('1F422'),
  'animal-frog':         OM('1F438'),
  'animal-fish':         OM('1F41F'),
  'animal-shark':        OM('1F988'),
  'animal-whale':        OM('1F40B'),
  'animal-dolphin':      OM('1F42C'),
  'animal-octopus':      OM('1F419'),
  'animal-jellyfish':    OM('1F9DF'),
  'animal-crab':         OM('1F980'),
  'animal-lobster':      OM('1F99E'),
  'animal-starfish':     OM('2B50'),
  'animal-butterfly':    OM('1F98B'),
  'animal-bee':          OM('1F41D'),
  'animal-ladybug':      OM('1F41E'),
  'animal-dragonfly':    OM('1F98B'),
  'animal-snail':        OM('1F40C'),
  'animal-spider':       OM('1F577'),
  'animal-hamster':      OM('1F439'),
  'animal-squirrel':     OM('1F43F'),
  'animal-hedgehog':     OM('1F994'),
  'animal-deer':         OM('1F98C'),
  'animal-monkey':       OM('1F412'),
  'animal-gorilla':      OM('1F98D'),
  'animal-cheetah':      OM('1F406'),
  'animal-leopard':      OM('1F406'),
  'animal-hippo':        OM('1F99B'),
  'animal-rhino':        OM('1F98F'),
  'animal-camel':        OM('1F42A'),
  'animal-kangaroo':     OM('1F998'),
  'animal-koala':        OM('1F428'),
  'animal-panda':        OM('1F43C'),
  'animal-polar-bear':   OM('1F43B'),
  'animal-seal':         OM('1F9AD'),
  'animal-toucan':       OM('1F99C'),
  'animal-arctic-fox':   OM('1F98A'),
  'animal-raccoon':      OM('1F99D'),
  'animal-bat':          OM('1F987'),

  // ══════════════════ FRUITS (fruit- prefix) ══════════════════
  'fruit-apple':        OM('1F34E'),
  'fruit-banana':       OM('1F34C'),
  'fruit-orange':       OM('1F34A'),
  'fruit-grapes':       OM('1F347'),
  'fruit-grape':        OM('1F347'),
  'fruit-strawberry':   OM('1F353'),
  'fruit-watermelon':   OM('1F349'),
  'fruit-pineapple':    OM('1F34D'),
  'fruit-mango':        OM('1F96D'),
  'fruit-cherries':     OM('1F352'),
  'fruit-cherry':       OM('1F352'),
  'fruit-lemon':        OM('1F34B'),
  'fruit-lime':         OM('1F34B'),
  'fruit-pear':         OM('1F350'),
  'fruit-peach':        OM('1F351'),
  'fruit-plum':         OM('1F351'),
  'fruit-raspberry':    OM('1F353'),
  'fruit-blueberry':    OM('1FAD0'),
  'fruit-blackberry':   OM('1FAD0'),
  'fruit-coconut':      OM('1F965'),
  'fruit-kiwi':         OM('1F95D'),
  'fruit-fig':          OM('1F350'),
  'fruit-pomegranate':  OM('1F34E'),
  'fruit-dragonfruit':  OM('1F34D'),
  'fruit-papaya':       OM('1F96D'),
  'fruit-avocado':      OM('1F951'),
  'fruit-guava':        OM('1F96D'),
  'fruit-melon':        OM('1F348'),
  'fruit-cantaloupe':   OM('1F348'),
  'fruit-honeydew':     OM('1F348'),
  'fruit-lychee':       OM('1F347'),
  'fruit-persimmon':    OM('1F34A'),
  'fruit-passionfruit': OM('1F351'),
  'fruit-tangerine':    OM('1F34A'),
  'fruit-apricot':      OM('1F351'),
  'fruit-starfruit':    OM('1F34B'),
  'fruit-grapefruit':   OM('1F34A'),
  'fruit-cranberry':    OM('1F353'),
  'fruit-date':         OM('1F334'),
  'fruit-jackfruit':    OM('1F34D'),
  'fruit-gooseberry':   OM('1FAD0'),
  'fruit-currant':      OM('1FAD0'),
  'fruit-elderberry':   OM('1FAD0'),
  'fruit-mangosteen':   OM('1F34E'),
  'fruit-tamarind':     OM('1F330'),
  'fruit-rambutan':     OM('1F347'),
  'fruit-longan':       OM('1F347'),
  'fruit-quince':       OM('1F350'),

  // ══════════════════ VEGETABLES (veg- prefix) ══════════════════
  'veg-carrot':       OM('1F955'),
  'veg-broccoli':     OM('1F966'),
  'veg-corn':         OM('1F33D'),
  'veg-tomato':       OM('1F345'),
  'veg-potato':       OM('1F954'),
  'veg-onion':        OM('1F9C5'),
  'veg-bell-pepper':  OM('1FAD1'),
  'veg-cucumber':     OM('1F952'),
  'veg-cauliflower':  OM('1F966'),
  'veg-eggplant':     OM('1F346'),
  'veg-mushroom':     OM('1F344'),
  'veg-garlic':       OM('1F9C4'),
  'veg-pumpkin':      OM('1F383'),
  'veg-radish':       OM('1F955'),
  'veg-asparagus':    OM('1F33F'),
  'veg-green-beans':  OM('1FAD8'),
  'veg-peas':         OM('1FAD8'),
  'veg-zucchini':     OM('1F952'),
  'veg-leek':         OM('1F9C5'),
  'veg-celery':       OM('1F33F'),
  'veg-sweet-potato': OM('1F360'),
};

// Categories that should show coloring-book style illustrations
export const PHOTO_CATEGORIES = new Set(['animals', 'fruits', 'vegetables']);

/**
 * Returns a coloring-book style illustration URL for the given item,
 * or null to fall back to the SVG coloring sheet preview.
 */
export function getPhotoUrl(id: string, category: string, title: string): string | null {
  if (!PHOTO_CATEGORIES.has(category)) return null;
  // Direct ID match
  if (PHOTO_MAP[id]) return PHOTO_MAP[id];
  // Title-based key match (lowercase with dashes)
  const titleKey = title.toLowerCase().replace(/\s+/g, '-');
  if (PHOTO_MAP[titleKey]) return PHOTO_MAP[titleKey];
  return null;
}
